export { default as Article } from './article/Article'
export { default as Feature } from './feature/Feature'
export { default as Brands } from './brands/Brands'
export { default as CTA } from './cta/CTA'
export { default as Navbar } from './navbar/Navbar'